workflows:
  ios-unsigned-build:
    name: Build Unsigned iOS App
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: default
      xcode: latest
      cocoapods: default
    scripts:
      - name: Instalar dependencias
        script: |
          flutter pub get
      - name: Build iOS unsigned app
        script: |
          # Usar el comando oficial de Flutter para crear un archivo de Xcode (.xcarchive) sin firmar
          flutter build ipa --release --no-codesign
          
          # El .xcarchive se guarda en build/ios/archive/Runner.xcarchive
          # Dentro está la aplicación compilada (Runner.app) lista para extraer
          mkdir -p Payload
          cp -r build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app Payload/
          zip -r -q app.ipa Payload
    artifacts:
      - app.ipa
