// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPVcrLqIQ5lziDAn99J0oqWJfziBoq98Y',
    appId: '1:471783177855:web:0376774b575078b9f4094a',
    messagingSenderId: '471783177855',
    projectId: 'instarecetas-8b6eb',
    authDomain: 'instarecetas-8b6eb.firebaseapp.com',
    storageBucket: 'instarecetas-8b6eb.firebasestorage.app',
    measurementId: 'G-F59C6MWSR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf5BK4BmCqqW-ORvoN0nmyExDtYzmHy-k',
    appId: '1:471783177855:android:22f4b02922c7d5c5f4094a',
    messagingSenderId: '471783177855',
    projectId: 'instarecetas-8b6eb',
    storageBucket: 'instarecetas-8b6eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3cieB4-KTJbIrAn6fGHVNJ-HS93Cklz0',
    appId: '1:471783177855:ios:10ceb783e99190c9f4094a',
    messagingSenderId: '471783177855',
    projectId: 'instarecetas-8b6eb',
    storageBucket: 'instarecetas-8b6eb.firebasestorage.app',
    iosBundleId: 'com.serga.recipecatcher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3cieB4-KTJbIrAn6fGHVNJ-HS93Cklz0',
    appId: '1:471783177855:ios:10ceb783e99190c9f4094a',
    messagingSenderId: '471783177855',
    projectId: 'instarecetas-8b6eb',
    storageBucket: 'instarecetas-8b6eb.firebasestorage.app',
    iosBundleId: 'com.serga.recipecatcher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPVcrLqIQ5lziDAn99J0oqWJfziBoq98Y',
    appId: '1:471783177855:web:ff4320304bb5f3ddf4094a',
    messagingSenderId: '471783177855',
    projectId: 'instarecetas-8b6eb',
    authDomain: 'instarecetas-8b6eb.firebaseapp.com',
    storageBucket: 'instarecetas-8b6eb.firebasestorage.app',
    measurementId: 'G-Y3D9K3W2M1',
  );
}
